"""create game catalog

Revision ID: 63f405c4c177
Revises:
Create Date: 2026-09-14 13:06:59.164455
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "63f405c4c177"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "games",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("slug", sa.String(length=350), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column("developers", sa.JSON(), nullable=False),
        sa.Column("publishers", sa.JSON(), nullable=False),
        sa.Column("categories", sa.JSON(), nullable=False),
        sa.Column("price", sa.JSON(), nullable=True),
        sa.Column("is_free", sa.Boolean(), nullable=True),
        sa.Column("achievement_count", sa.Integer(), nullable=True),
        sa.Column("system_requirements", sa.JSON(), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_games_slug"), "games", ["slug"], unique=False)
    op.create_index("ix_games_title", "games", ["title"], unique=False)
    op.create_table(
        "genres",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "platforms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "game_external_ids",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("external_id", sa.String(length=120), nullable=False),
        sa.Column("external_url", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider", "external_id", name="uq_game_external_provider_id"
        ),
    )
    op.create_index(
        op.f("ix_game_external_ids_game_id"),
        "game_external_ids",
        ["game_id"],
        unique=False,
    )
    op.create_table(
        "game_genres",
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("genre_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["genre_id"], ["genres.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("game_id", "genre_id"),
    )
    op.create_table(
        "game_platforms",
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("platform_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["platform_id"], ["platforms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("game_id", "platform_id"),
    )
    op.create_table(
        "game_ratings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("max_score", sa.Float(), nullable=False),
        sa.Column("rating_count", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("game_id", "source", name="uq_game_rating_source"),
    )
    op.create_index(
        "ix_game_ratings_game_id", "game_ratings", ["game_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_game_ratings_game_id", table_name="game_ratings")
    op.drop_table("game_ratings")
    op.drop_table("game_platforms")
    op.drop_table("game_genres")
    op.drop_index(op.f("ix_game_external_ids_game_id"), table_name="game_external_ids")
    op.drop_table("game_external_ids")
    op.drop_table("platforms")
    op.drop_table("genres")
    op.drop_index("ix_games_title", table_name="games")
    op.drop_index(op.f("ix_games_slug"), table_name="games")
    op.drop_table("games")
    # ### end Alembic commands ###
